name: Discord Notify

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Data
        id: commit
        run: |
          RESPONSE=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits)

          SHA=$(echo "$RESPONSE" | jq -r '.[0].sha')

          COMMIT=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/$SHA)

          FILES=$(echo "$COMMIT" | jq '.files | length')
          ADD=$(echo "$COMMIT" | jq '.stats.additions')
          DEL=$(echo "$COMMIT" | jq '.stats.deletions')
          DATE=$(echo "$COMMIT" | jq -r '.commit.author.date')

          SHORT_SHA=$(echo "$SHA" | cut -c1-7)

          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "add=$ADD" >> $GITHUB_OUTPUT
          echo "del=$DEL" >> $GITHUB_OUTPUT
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "fullsha=$SHA" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Build Status
        id: status
        run: |
          NOW=$(date -u +%s)
          COMMIT_TIME=$(date -d "${{ steps.commit.outputs.date }}" +%s)

          DIFF=$((NOW - COMMIT_TIME))
          MINUTES=$((DIFF / 60))

          if [ $MINUTES -ge 20 ]; then
            echo "mode=stable" >> $GITHUB_OUTPUT
          else
            echo "mode=update" >> $GITHUB_OUTPUT
          fi

      - name: Send / Edit Discord Message
        run: |
          MODE="${{ steps.status.outputs.mode }}"

          if [ "$MODE" = "update" ]; then

            curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"@everyone\",
              \"embeds\": [{
                \"title\": \"Vencord Updated\",
                \"color\": 9605778,
                \"fields\": [
                  {
                    \"name\": \"Author\",
                    \"value\": \"<@375402345971974147>\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"Status\",
                    \"value\": \"Files Changed: ${{ steps.commit.outputs.files }}\nAdditions: ${{ steps.commit.outputs.add }}\nDeletions: ${{ steps.commit.outputs.del }}\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"System\",
                    \"value\": \"Updated\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"Comment\",
                    \"value\": \"[Commit ${{ steps.commit.outputs.sha }}](https://github.com/${{ github.repository }}/commit/${{ steps.commit.outputs.fullsha }})\",
                    \"inline\": false
                  }
                ],
                \"footer\": {
                  \"text\": \"Vencord Update\"
                }
              }]
            }" \
            ${{ secrets.DISCORD_WEBHOOK }}

          else

            NOW=$(date -u +%s)
            COMMIT_TIME=$(date -d "${{ steps.commit.outputs.date }}" +%s)
            DIFF=$((NOW - COMMIT_TIME))
            MINUTES=$((DIFF / 60))

            LAST_UPDATE="Before $MINUTES minutes ago"

            curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"\",
              \"embeds\": [{
                \"title\": \"Vencord Status\",
                \"color\": 657930,
                \"fields\": [
                  {
                    \"name\": \"Author\",
                    \"value\": \"<@375402345971974147>\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"Status\",
                    \"value\": \"Ahead ✅\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"System\",
                    \"value\": \"Ready\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"Last Update\",
                    \"value\": \"$LAST_UPDATE\",
                    \"inline\": false
                  }
                ],
                \"footer\": {
                  \"text\": \"Vencord Status\"
                }
              }]
            }" \
            ${{ secrets.DISCORD_WEBHOOK }}

          fi
