name: Discord Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "@everyone",
            "embeds": [{
              "title": "Vencord Updated!",
              "description": "Update Now !!",
              "color": 3447003,
              "fields": [
                {
                  "name": "Author",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Commit",
                  "value": "${{ github.event.head_commit.message }}"
                },
                {
                  "name": "Link",
                  "value": "${{ github.event.head_commit.url }}"
                }
              ],
              "footer": {
                "text": "GitHub Action"
              }
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
